"""Rule, geometry, learning, and small-file CLI tests for Project 11."""

import unittest

# Only parsing SVGs generated by these tests, never untrusted XML.
import xml.etree.ElementTree as ET  # nosec B405
from collections import deque
from dataclasses import replace
from io import StringIO
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch

from reinforcement_learning.projects.project011 import (
    MOVE_ACTIONS,
    Action,
    GameState,
    Hex,
    HexEnvironment,
    HexMap,
    Outcome,
    QLearningAgent,
    Rules,
    StepResult,
    Terrain,
    allowed_actions,
    barbarian_attack_probability,
    combat_damage,
    main,
    run_episode,
    save_svg,
)


def plains_map(
    *,
    width: int = 12,
    height: int = 5,
    city1: Hex | None = None,
    city2: Hex | None = None,
    terrain: dict[Hex, Terrain] | None = None,
) -> HexMap:
    special = terrain or {}
    return HexMap(
        tuple(tuple(special.get(Hex(col, row), Terrain.PLAINS) for col in range(width)) for row in range(height)),
        city1 if city1 is not None else Hex(1, 2),
        city2 if city2 is not None else Hex(6, 2),
    )


class TestHexMap(unittest.TestCase):
    def test_default_map_is_fixed_twenty_by_twenty_with_cities_ten_hexes_apart(self) -> None:
        board = HexMap.generate()
        self.assertEqual((board.width, board.height), (20, 20))
        self.assertEqual(board.distance(board.city1, board.city2), 10)
        self.assertEqual({terrain for row in board.tiles for terrain in row}, set(Terrain))
        for city in (board.city1, board.city2):
            self.assertEqual(board.tiles[city.row][city.col], Terrain.PLAINS)
        self.assertEqual(board, HexMap.generate())
        self.assertNotEqual(board.tiles, HexMap.generate(7).tiles)
        env = HexEnvironment(board)
        starts = {env.reset().barbarian for _ in range(20)}
        self.assertGreater(len(starts), 1)
        self.assertNotIn(board.city1, starts)
        self.assertIs(env.board, board)
        self.assertEqual(env.board, HexMap.generate())

    def test_even_and_odd_rows_have_correct_six_reciprocal_neighbors(self) -> None:
        board = plains_map()
        expected = {
            Hex(3, 2): (Hex(4, 2), Hex(3, 1), Hex(2, 1), Hex(2, 2), Hex(2, 3), Hex(3, 3)),
            Hex(3, 1): (Hex(4, 1), Hex(4, 0), Hex(3, 0), Hex(2, 1), Hex(3, 2), Hex(4, 2)),
        }
        for origin, neighbors in expected.items():
            with self.subTest(origin=origin):
                self.assertEqual(board.neighbors(origin), neighbors)
                for action, target in zip(MOVE_ACTIONS, neighbors, strict=True):
                    self.assertEqual(board.neighbor(target, Action((action + 3) % 6)), origin)

    def test_east_west_wrap_indefinitely_but_north_south_do_not(self) -> None:
        board = plains_map()
        self.assertEqual(board.neighbor(Hex(0, 2), Action.WEST), Hex(11, 2))
        self.assertEqual(board.neighbor(Hex(11, 2), Action.EAST), Hex(0, 2))
        tile = Hex(1, 2)
        for _ in range(board.width * 100):
            next_tile = board.neighbor(tile, Action.EAST)
            self.assertIsNotNone(next_tile)
            if next_tile is None:
                self.fail("Eastward movement was blocked")
            tile = next_tile
        self.assertEqual(tile, Hex(1, 2))
        for action in (Action.NORTHEAST, Action.NORTHWEST):
            self.assertIsNone(board.neighbor(Hex(3, 0), action))
        for action in (Action.SOUTHEAST, Action.SOUTHWEST):
            self.assertIsNone(board.neighbor(Hex(3, 4), action))

    def test_wrapped_distance_matches_graph_search_including_seams_and_edges(self) -> None:
        board = plains_map(width=5, height=4, city2=Hex(4, 2))
        for row in range(board.height):
            for col in range(board.width):
                start = Hex(col, row)
                distances = {start: 0}
                queue = deque([start])
                while queue:
                    current = queue.popleft()
                    for neighbor in board.neighbors(current):
                        if neighbor not in distances:
                            distances[neighbor] = distances[current] + 1
                            queue.append(neighbor)
                self.assertEqual(len(distances), 20)
                for target, distance in distances.items():
                    self.assertEqual(board.distance(start, target), distance)

    def test_invalid_maps_and_geometry_inputs(self) -> None:
        for rows in ((), ((Terrain.PLAINS,) * 2,), ((Terrain.PLAINS,) * 3, (Terrain.FOREST,))):
            with self.subTest(rows=rows), self.assertRaises(ValueError):
                HexMap(rows, Hex(0, 0), Hex(1, 0))
        for city in (Hex(-1, 0), Hex(12, 2), Hex(1, 2)):
            with self.subTest(city=city), self.assertRaises(ValueError):
                plains_map(city2=city)
        board = plains_map()
        with self.assertRaises(ValueError):
            board.neighbor(board.city1, Action.REST)
        with self.assertRaises(ValueError):
            board.distance(Hex(0, -1), board.city2)


class TestMovementAndTurns(unittest.TestCase):
    def test_two_plains_moves_share_one_turn_and_one_turn_penalty(self) -> None:
        env = HexEnvironment(plains_map())
        env.reset(barbarian_health=0)
        first = env.step(Action.EAST)
        self.assertEqual((first.state.player, first.state.moves_left, first.state.turns_elapsed), (Hex(2, 2), 1, 0))
        self.assertEqual(first.reward, 0)
        second = env.step(Action.EAST)
        self.assertEqual((second.state.player, second.state.moves_left, second.state.turns_elapsed), (Hex(3, 2), 2, 1))
        self.assertEqual(second.reward, -1)
        self.assertFalse(second.done)

    def test_rough_terrain_ends_turn_even_with_only_one_move_left(self) -> None:
        for terrain in (Terrain.FOREST, Terrain.MOUNTAIN):
            for plains_first in (False, True):
                with self.subTest(terrain=terrain, plains_first=plains_first):
                    destination = Hex(3 if plains_first else 2, 2)
                    env = HexEnvironment(plains_map(terrain={destination: terrain}))
                    env.reset(barbarian_health=0)
                    if plains_first:
                        env.step(Action.EAST)
                    result = env.step(Action.EAST)
                    self.assertEqual(result.state.player, destination)
                    self.assertEqual(result.state.turns_elapsed, 1)
                    self.assertEqual(result.state.moves_left, 2)
                    self.assertEqual(result.reward, -1)

    def test_illegal_move_has_no_state_or_randomness_side_effects(self) -> None:
        board = plains_map(city1=Hex(0, 0))
        left, right = HexEnvironment(board, seed=5), HexEnvironment(board, seed=5)
        state = left.reset()
        self.assertEqual(state, right.reset())
        for action in (Action.NORTHWEST, Action.NORTHEAST, Action.ATTACK):
            with self.subTest(action=action), self.assertRaises(ValueError):
                left.step(action)
            self.assertEqual(left.state, state)
        self.assertEqual(left.step(Action.REST), right.step(Action.REST))

    def test_occupied_tiles_block_movement_but_allow_adjacent_attacks(self) -> None:
        env = HexEnvironment(plains_map())
        state = env.reset(barbarian_position=Hex(2, 2))
        actions = allowed_actions(env.board, state)
        self.assertNotIn(Action.EAST, actions)
        self.assertIn(Action.ATTACK, actions)
        with self.assertRaises(ValueError):
            env.step(Action.EAST)
        self.assertEqual(env.state, state)

    def test_rest_heals_ten_caps_at_one_hundred_and_can_end_partial_turn(self) -> None:
        for health, expected in ((40, 50), (95, 100), (100, 100)):
            with self.subTest(health=health):
                env = HexEnvironment(plains_map())
                env.reset(player_health=health, barbarian_health=0)
                env.step(Action.EAST)
                result = env.step(Action.REST)
                self.assertEqual(result.state.player_health, expected)
                self.assertEqual(result.state.turns_elapsed, 1)
                self.assertEqual(result.reward, -1)

    def test_arrival_counts_partial_turn_and_ends_before_enemy_response(self) -> None:
        board = plains_map(city2=Hex(2, 2))
        env = HexEnvironment(board, rules=Rules(max_turns=1))
        env.reset(player_health=1, barbarian_position=Hex(2, 1))
        with patch.object(env._rng, "choice", side_effect=AssertionError("Unexpected enemy turn")):
            result = env.step(Action.EAST)
        self.assertEqual(result.state.outcome, Outcome.SUCCESS)
        self.assertTrue(result.terminated)
        self.assertFalse(result.truncated)
        self.assertEqual((result.state.turns_elapsed, result.state.player_health, result.reward), (1, 1, 99))
        self.assertEqual(result.state.barbarian_health, 100)
        self.assertEqual(allowed_actions(board, result.state), ())
        with self.assertRaises(RuntimeError):
            env.step(Action.REST)

    def test_goal_is_allowed_on_the_second_move_of_the_last_turn(self) -> None:
        env = HexEnvironment(plains_map(city2=Hex(3, 2)), rules=Rules(max_turns=1))
        env.reset(barbarian_health=0)
        self.assertFalse(env.step(Action.EAST).done)
        result = env.step(Action.EAST)
        self.assertEqual(result.state.outcome, Outcome.SUCCESS)
        self.assertEqual(result.state.turns_elapsed, 1)

    def test_timeout_occurs_after_exactly_five_hundred_full_turns(self) -> None:
        env = HexEnvironment(plains_map())
        env.reset(barbarian_health=0)
        total = 0.0
        for turn in range(1, 501):
            result = env.step(Action.REST)
            total += result.reward
            self.assertEqual(result.state.turns_elapsed, turn)
            self.assertEqual(result.done, turn == 500)
        self.assertTrue(result.truncated)
        self.assertFalse(result.terminated)
        self.assertEqual(result.state.outcome, Outcome.TIMEOUT)
        self.assertEqual(total, -1500)

    def test_movement_and_attacks_work_across_horizontal_seam(self) -> None:
        board = plains_map(city1=Hex(0, 2), city2=Hex(6, 2))
        env = HexEnvironment(board)
        state = env.reset(barbarian_position=Hex(11, 2))
        self.assertIn(Action.ATTACK, allowed_actions(board, state))
        self.assertNotIn(Action.WEST, allowed_actions(board, state))
        env.reset(barbarian_health=0)
        result = env.step(Action.WEST)
        self.assertEqual(result.state.player, Hex(11, 2))
        self.assertEqual(result.state.moves_left, 1)

    def test_ten_plains_tiles_take_five_turns_not_ten_decisions_of_penalty(self) -> None:
        env = HexEnvironment(plains_map(width=20, city2=Hex(11, 2)))
        env.reset(barbarian_health=0)
        total = 0.0
        for _ in range(10):
            result = env.step(Action.EAST)
            total += result.reward
        self.assertEqual(result.state.outcome, Outcome.SUCCESS)
        self.assertEqual(result.state.turns_elapsed, 5)
        self.assertEqual(total, 95)

    def test_lifecycle_reset_health_and_rule_validation(self) -> None:
        env = HexEnvironment(plains_map())
        with self.assertRaises(RuntimeError):
            env.step(Action.EAST)
        for health in (-1, 0, 101, True):
            with self.subTest(health=health), self.assertRaises(ValueError):
                env.reset(player_health=health)
        for tile in (env.board.city1, Hex(-1, 1), Hex(12, 0)):
            with self.subTest(tile=tile), self.assertRaises(ValueError):
                env.reset(barbarian_position=tile)
        for rules in ({"max_turns": 0}, {"heal_amount": 0}, {"city_damage": -1}, {"city_radius": -1}):
            with self.subTest(rules=rules), self.assertRaises(ValueError):
                Rules(**rules)
        env.reset(barbarian_health=0)
        env.step(Action.EAST)
        state = env.reset()
        self.assertEqual((state.player, state.player_health, state.barbarian_health), (env.board.city1, 100, 100))
        self.assertEqual((state.turns_elapsed, state.moves_left), (0, 2))


class TestCombatAndCities(unittest.TestCase):
    def test_attack_probability_uses_absolute_remaining_health_not_health_ratio(self) -> None:
        for barbarian, player, expected in ((91, 90, 1.0), (89, 90, 0.89), (90, 90, 0.9), (0, 90, 0), (100, 100, 1)):
            with self.subTest(barbarian=barbarian, player=player):
                self.assertEqual(barbarian_attack_probability(barbarian, player), expected)
        with self.assertRaises(ValueError):
            barbarian_attack_probability(101, 100)

    def test_damage_scales_with_both_health_values_and_is_clamped(self) -> None:
        for attacker, defender, expected in ((100, 100, 30), (50, 100, 15), (100, 50, 50), (1, 100, 1), (100, 1, 1)):
            with self.subTest(attacker=attacker, defender=defender):
                self.assertEqual(combat_damage(attacker, defender), expected)
        with self.assertRaises(ValueError):
            combat_damage(0, 100)

    def test_player_attack_uses_injected_damage_and_kills_before_barbarian_phase(self) -> None:
        calls: list[tuple[int, int]] = []

        def damage(attacker: int, defender: int) -> int:
            calls.append((attacker, defender))
            return 1000

        env = HexEnvironment(plains_map(), damage_function=damage)
        env.reset(player_health=80, barbarian_position=Hex(2, 2), barbarian_health=40)
        with patch.object(env._rng, "random", side_effect=AssertionError("Dead enemy attacked")):
            result = env.step(Action.ATTACK)
            for _ in range(4):
                env.step(Action.REST)
        self.assertEqual(calls, [(80, 40)])
        self.assertEqual(
            (result.state.barbarian, result.state.barbarian_health, result.state.player_health), (None, 0, 80)
        )
        self.assertEqual(result.state.turns_elapsed, 1)
        self.assertIsNone(env.state.barbarian)

    def test_surviving_barbarian_uses_updated_health_for_its_normal_response(self) -> None:
        calls: list[tuple[int, int]] = []

        def damage(attacker: int, defender: int) -> int:
            calls.append((attacker, defender))
            return combat_damage(attacker, defender)

        env = HexEnvironment(plains_map(), rules=Rules(city_damage=0), damage_function=damage)
        env.reset(player_health=80, barbarian_position=Hex(3, 2))
        env.step(Action.EAST)
        with patch.object(env._rng, "random", return_value=0.75) as attack_roll:
            result = env.step(Action.ATTACK)
        self.assertEqual(calls, [(80, 100), (76, 80)])
        self.assertEqual((result.state.player_health, result.state.barbarian_health), (52, 76))
        self.assertEqual(result.state.turns_elapsed, 1)
        attack_roll.assert_called_once()

    def test_barbarian_probability_boundaries_and_at_most_one_attack_roll(self) -> None:
        for enemy_health, roll, attacks in ((91, 0.999, True), (89, 0.889, True), (89, 0.89, False), (90, 0.9, False)):
            with self.subTest(enemy_health=enemy_health, roll=roll):
                env = HexEnvironment(plains_map(), rules=Rules(city_damage=0))
                env.reset(player_health=80, barbarian_position=Hex(3, 2), barbarian_health=enemy_health)
                env.step(Action.EAST)
                with (
                    patch.object(env._rng, "random", return_value=roll) as attack_roll,
                    patch.object(env._rng, "choice", return_value=Hex(3, 2)) as roam,
                ):
                    result = env.step(Action.REST)  # Player heals to exactly 90 before the enemy phase.
                expected = 90 - combat_damage(enemy_health, 90) if attacks else 90
                self.assertEqual(result.state.player_health, expected)
                attack_roll.assert_called_once()
                self.assertEqual(roam.call_count, 0 if attacks else 1)

    def test_barbarian_moves_one_rough_hex_then_can_attack_but_does_not_act_mid_turn(self) -> None:
        board = plains_map(terrain={Hex(3, 2): Terrain.MOUNTAIN})
        env = HexEnvironment(board, rules=Rules(city_damage=0))
        state = env.reset(barbarian_position=Hex(4, 2))
        partial = env.step(Action.EAST)
        self.assertEqual(partial.state.barbarian, state.barbarian)
        with patch.object(env._rng, "choice", return_value=Hex(3, 2)), patch.object(env._rng, "random", return_value=0):
            result = env.step(Action.REST)
        self.assertEqual(result.state.barbarian, Hex(3, 2))
        self.assertEqual(result.state.player_health, 70)
        self.assertEqual(result.state.turns_elapsed, 1)

    def test_city_one_protection_and_city_fire_can_kill_enemy_without_respawn(self) -> None:
        env = HexEnvironment(plains_map())
        enemy = Hex(2, 2)
        env.reset(player_health=1, barbarian_position=enemy)
        with (
            patch.object(env._rng, "choice", return_value=enemy),
            patch.object(env._rng, "random", side_effect=AssertionError("Protected player was attacked")),
        ):
            for turn, enemy_health in enumerate((70, 40, 10, 0), start=1):
                result = env.step(Action.REST)
                self.assertEqual(result.state.player_health, 1 + 10 * turn)
                self.assertEqual(result.state.barbarian_health, enemy_health)
            self.assertIsNone(result.state.barbarian)
            self.assertIsNone(env.step(Action.REST).state.barbarian)

    def test_city_radius_two_is_inclusive_at_both_cities(self) -> None:
        board = plains_map(width=20, height=7, city1=Hex(1, 3), city2=Hex(11, 3))
        for position, expected in (
            (Hex(3, 3), 70),
            (Hex(4, 3), 100),
            (Hex(9, 3), 70),
            (Hex(8, 3), 100),
            (Hex(19, 3), 70),
        ):
            with self.subTest(position=position):
                env = HexEnvironment(board)
                env.reset(barbarian_position=position)
                with patch.object(env._rng, "choice", return_value=position):
                    self.assertEqual(env.step(Action.REST).state.barbarian_health, expected)

    def test_city_damage_uses_ending_position_and_overlapping_radii_do_not_stack(self) -> None:
        board = plains_map(width=20, height=7, city1=Hex(1, 3), city2=Hex(11, 3))
        for start, finish, expected in ((Hex(3, 3), Hex(4, 3), 100), (Hex(4, 3), Hex(3, 3), 70)):
            with self.subTest(start=start):
                env = HexEnvironment(board)
                env.reset(barbarian_position=start)
                with patch.object(env._rng, "choice", return_value=finish):
                    self.assertEqual(env.step(Action.REST).state.barbarian_health, expected)
        env = HexEnvironment(plains_map(city2=Hex(4, 2)))
        env.reset(barbarian_position=Hex(2, 2))
        with patch.object(env._rng, "choice", return_value=Hex(2, 2)):
            self.assertEqual(env.step(Action.REST).state.barbarian_health, 70)

    def test_player_death_precedes_timeout_and_city_fire_still_finishes(self) -> None:
        env = HexEnvironment(plains_map(), rules=Rules(max_turns=1))
        env.reset(player_health=1, barbarian_health=30, barbarian_position=Hex(3, 2))
        env.step(Action.EAST)
        with patch.object(env._rng, "random", return_value=0.999):
            result = env.step(Action.REST)
        self.assertEqual(result.state.outcome, Outcome.DEATH)
        self.assertEqual((result.state.player_health, result.state.barbarian_health), (0, 0))
        self.assertIsNone(result.state.barbarian)
        self.assertEqual(result.reward, -1001)
        self.assertTrue(result.terminated)
        self.assertFalse(result.truncated)


class TestLearningAndReports(unittest.TestCase):
    def test_masks_cover_exploration_greedy_behavior_and_bootstrap_targets(self) -> None:
        board = plains_map(city1=Hex(1, 0))
        env = HexEnvironment(board)
        state = env.reset(barbarian_health=0)
        agent = QLearningAgent(board, epsilon=0, alpha=0.5)
        agent.q[agent.key(state)] = [0.0] * len(Action)
        agent.q[agent.key(state)][Action.NORTHWEST] = 1000
        agent.q[agent.key(state)][Action.EAST] = 1
        self.assertEqual(agent.choose_action(state), Action.EAST)
        agent.epsilon = 1
        for _ in range(100):
            self.assertIn(agent.choose_action(state), allowed_actions(board, state))
        result = env.step(Action.EAST)
        agent.q[agent.key(result.state)] = [0.0] * len(Action)
        agent.q[agent.key(result.state)][Action.NORTHWEST] = 1000
        agent.q[agent.key(result.state)][Action.EAST] = 4
        target = 4 + agent.potential(result.state) - agent.potential(state)
        agent.learn(state, Action.EAST, result)
        self.assertAlmostEqual(agent.q[agent.key(state)][Action.EAST], 1 + 0.5 * (target - 1))

    def test_terminal_targets_do_not_bootstrap_including_time_limit(self) -> None:
        board = plains_map(city2=Hex(2, 2))
        for action, outcome in ((Action.EAST, Outcome.SUCCESS), (Action.REST, Outcome.TIMEOUT)):
            with self.subTest(outcome=outcome):
                rules = Rules(max_turns=1)
                env = HexEnvironment(board, rules=rules)
                state = env.reset(barbarian_health=0)
                agent = QLearningAgent(board, rules=rules, alpha=1)
                result = env.step(action)
                self.assertEqual(result.state.outcome, outcome)
                agent.q[agent.key(result.state)] = [1000.0] * len(Action)
                agent.learn(state, action, result)
                self.assertEqual(agent.q[agent.key(state)][action], result.reward - agent.potential(state))

    def test_shaping_adds_same_constant_to_success_and_failure_episode_returns(self) -> None:
        board = plains_map(city2=Hex(3, 2))
        rules = Rules(max_turns=2)
        for actions in ((Action.EAST, Action.EAST), (Action.REST, Action.REST)):
            env = HexEnvironment(board, rules=rules)
            state = env.reset(barbarian_health=0)
            agent = QLearningAgent(board, rules=rules)
            shaped = actual = 0.0
            for action in actions:
                result = env.step(action)
                actual += result.reward
                shaped += result.reward + agent.potential(result.state) - agent.potential(state)
                state = result.state
            self.assertTrue(result.done)
            self.assertAlmostEqual(shaped - actual, 1)

    def test_state_aggregation_keeps_nearby_threat_health_movement_and_final_horizon(self) -> None:
        board = plains_map()
        agent = QLearningAgent(board)
        state = GameState(board.city1, 90, Hex(2, 2), 89)
        for alternative in (
            replace(state, player_health=89),
            replace(state, barbarian_health=90),
            replace(state, barbarian=Hex(3, 2)),
            replace(state, moves_left=1),
            replace(state, turns_elapsed=499),
        ):
            self.assertNotEqual(agent.key(state), agent.key(alternative))
        self.assertEqual(agent.key(replace(state, barbarian=Hex(6, 2))), agent.key(replace(state, barbarian=Hex(7, 2))))

    def test_seeded_training_is_reproducible_and_evaluation_does_not_change_estimates(self) -> None:
        board = HexMap.generate()
        rules = Rules(max_turns=20)
        left, right = HexEnvironment(board, rules=rules, seed=9), HexEnvironment(board, rules=rules, seed=9)
        a, b = QLearningAgent(board, rules=rules, seed=10), QLearningAgent(board, rules=rules, seed=10)
        for _ in range(5):
            self.assertEqual(run_episode(left, a), run_episode(right, b))
        self.assertEqual(a.q, b.q)
        saved = {key: list(values) for key, values in a.q.items()}
        trace: list[GameState] = []
        episode = run_episode(left, a, learn=False, trace=trace)
        self.assertEqual(a.q, saved)
        self.assertNotEqual(episode.outcome, Outcome.RUNNING)
        self.assertLessEqual(episode.decisions, rules.max_turns * 2)
        self.assertEqual(len(trace), episode.decisions + 1)
        for state in trace:
            self.assertTrue(board.contains(state.player))
            self.assertTrue(0 <= state.player_health <= 100)
            self.assertTrue(0 <= state.barbarian_health <= 100)
            if state.barbarian is not None:
                self.assertTrue(board.contains(state.barbarian))
                self.assertNotEqual(state.barbarian, state.player)
            else:
                self.assertEqual(state.barbarian_health, 0)

    def test_invalid_agent_parameters_illegal_updates_and_mismatched_rules(self) -> None:
        board = plains_map()
        for kwargs in ({"alpha": 0}, {"alpha": float("nan")}, {"epsilon": -1}, {"epsilon": float("inf")}):
            with self.subTest(kwargs=kwargs), self.assertRaises(ValueError):
                QLearningAgent(board, **kwargs)
        env, agent = HexEnvironment(board), QLearningAgent(board)
        state = env.reset(barbarian_health=0)
        with self.assertRaises(ValueError):
            agent.learn(state, Action.ATTACK, StepResult(state, 0))
        with self.assertRaises(ValueError):
            agent.learn(state, Action.REST, StepResult(state, float("nan")))
        self.assertFalse(agent.q)
        with self.assertRaises(ValueError):
            run_episode(HexEnvironment(board, rules=Rules(max_turns=1)), agent)

    def test_svg_has_four_hundred_hexagons_city_labels_and_unit_health(self) -> None:
        board = HexMap.generate()
        state = HexEnvironment(board).reset()
        with TemporaryDirectory() as directory:
            path = Path(directory) / "nested" / "map.svg"
            save_svg(board, state, path)
            # This is our own generated local SVG, not untrusted XML.
            root = ET.fromstring(path.read_text(encoding="utf-8"))  # nosec B314
        namespace = {"svg": "http://www.w3.org/2000/svg"}
        self.assertEqual(len(root.findall(".//svg:polygon", namespace)), 400)
        text = [element.text for element in root.findall(".//svg:text", namespace)]
        self.assertIn("C1", text)
        self.assertIn("C2", text)
        self.assertIn("P", text)
        self.assertIn("B", text)
        self.assertIn("100 HP", text)

    def test_cli_writes_only_small_reports_and_runs_training_and_evaluation_separately(self) -> None:
        with TemporaryDirectory() as directory:
            with (
                patch(
                    "sys.argv",
                    ["project011", "--episodes", "2", "--evaluate", "3", "--max-turns", "5", "--output-dir", directory],
                ),
                patch("sys.stdout", new_callable=StringIO),
            ):
                main()
            files = {path.name for path in Path(directory).iterdir()}
            self.assertEqual(files, {"map.svg", "episode.svg", "summary.md"})
            report = (Path(directory) / "summary.md").read_text(encoding="utf-8")
            self.assertIn("Training (2 episodes)", report)
            self.assertIn("Evaluation (3 episodes)", report)
            for path in Path(directory).iterdir():
                self.assertLess(path.stat().st_size, 150000)


if __name__ == "__main__":
    unittest.main()
